sudo: false
language: ruby
before_script:
- chmod +x "./build.sh"
script: "./build.sh"
branches:
  only:
  - source
rvm:
- 2.2.3
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: Ndei8hQU1V8zzcH/f/zgPtqRRRSt80Kfbu1HCRv17qUWb4YOGuKG0/+EXB3yr4XiT00fZdee/7ZeycwQcm2HVNbhEXKHiuj6caMjo8YQ3jwZhMY9nmhtBNH7dYPsjZYp3+lBhf98Bd3X+ieHXcl226S/m+E20R5fraXY/1C7B8atVK74rQsFvJ3h1zjyW5wkDfcNAJcrUxNwbQXJAgNd3hHRF8Kq1yYXxtwtqKv7C1Tto7Ltc/fKdo0u1Y6iApvZCYdv3ZUxVD4lEYKNqjbKLqw3dk5SN9F9MnDNw9Id26fwdu4CTQpYsAsYThdAmJIu234QLRGyfefv7J5m4OFlTbC4PsR1B+TzrMb7KhH9E9vroQ0WYkOsuLmx9bgZ6HvjoP+6Xc1tKH2LsV8Fg8RGhjs+P1xGGmLK8LVlbtAMSORb8Dl5JKEkRmphjdl7mx4l4nkX3x7cFDevFQ/mAEs/AW4S0tIPYOUIZk65436UYrj2YpLKoLZXpJBqvhm8SdT2sFcOURMzewTMln/bKFwE1bbyWLBqARFsCTjJWQZp0ugrwjTtw/l80Cb4j3KiTVxLwgRnOY+3U3/oM5kUDZSIS4qrdgs/6/vEtlgcoqBxMcMqks2oqcpkPgsmFYvtMQ8N5thnHI/6hgX0zdjHitOtklYSvFwrtFYr1LNzAxUugcg=
