# --- Global site settings --- #
url: "http://mlota.github.io"
baseurl: ""
title: Mel Lota
description: Web development, Microsoft Technologies and Raspberry Pi Hacking
email: melvin@auronmedia.co.uk

twitter_username: mlota
github_username:  mlota

# --- Navigation bar --- #
avatar: "/img/avatar-icon.png"

# List of links in the navigation bar
navbar-links:
  Home: ""
  About: "about"
  Contact: "contact"

# --- Footer options --- #
author:
  name: Mel Lota
  email: "melvin@auronmedia.co.uk"
  facebook: mel.lota
  github: mlota
  twitter: mlota
  linkedin: in/melvinlota
  stackoverflow: users/342940/mel-lota
 
# Select which links to show in the footer
footer-links-active:
  rss: false
  facebook: true
  email: true
  twitter: true
  github: true
  linkedin: false
  stackoverflow: false

# --- Misc --- #

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
disqus: "mlota"

# Fill in your Google Analytics ID to track your website using GA
google_analytics: "UA-15238345-6"

# Output options (more information on Jekyll's site)
timezone: "Europe/London"
markdown: kramdown
highlighter: rouge
paginate: 5
gems: [jekyll-paginate]

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true  # add comments to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "default"

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Files to be excluded from the production site
exclude: ['vendor','Gemfile','Gemfile.lock','README.md','build.sh','compile.sh','serve.sh']